[package]
name = "abc129"
version = "0.1.0"
authors = ["masa <masatoshi.sboard@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
